.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test()'
Julia 1.5:
  tags:
    - shared
  image: julia:1.5
  extends:
    - .script
pages:
  image: julia:1.5
  stage: deploy
  script:
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using MultiObjectiveProblems
        doctest(MultiObjectiveProblems)
        include("docs/make.jl")'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - shared
