name = "MultiObjectiveProblems"
uuid = "ad069600-9bf0-4bd3-b060-bd43ee6ba39c"
authors = ["Manuel Berkemeier <manuelbb@math.upb.de>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
